[phases.setup]
nixPkgs = ["nodejs_20", "python311", "gcc", "gnumake", "libtool", "autoconf", "automake"]

[phases.install]
cmds = ["npm install --build-from-source"]

[start]
cmd = "node server/index.js"
